# Generated by Django 4.2.16 on 2024-12-02 10:22

from django.db import migrations, models
import django.db.models.deletion
import users.Utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=users.Utils.user_directory_path),
        ),
    ]
