# Generated by Django 4.2.16 on 2024-12-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listing_brand_listing_color_listing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='engine',
            field=models.CharField(max_length=128),
        ),
    ]
